In [2]:
import pandas as pd
import numpy as np
import torch                        
import torch.nn as nn                
import torch.nn.functional as F      
from torch.utils.data import DataLoader, TensorDataset 
import os

In [3]:
csv_folder = '../data/Processed_Network_dataset'
normal_data_csv = "../data/normal_data.csv"
all_network_data_csv = "../data/all_network_data.csv"

file = os.path.join(csv_folder,"Network_dataset_1.csv")
print("file is ",file)
df = pd.read_csv(file)
df.head()

file is  ../data/Processed_Network_dataset\Network_dataset_1.csv

C:\Users\ACER\AppData\Local\Temp\ipykernel_18952\2066326535.py:7: DtypeWarning: Columns (0: src_bytes) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

,ts,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,...,http_response_body_len,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type
0,1554198358,3.122.49.24,1883,192.168.1.152,52976,tcp,-,80549.530260,1762852,41933215,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
1,1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,0,normal
2,1554198359,192.168.1.152,1880,192.168.1.152,51782,tcp,-,0.000000,0,0,...,0,0,-,-,-,bad_TCP_checksum,-,F,0,normal
3,1554198359,192.168.1.152,34296,192.168.1.152,10502,tcp,-,0.000000,0,0,...,0,0,-,-,-,-,-,-,0,normal
4,1554198362,192.168.1.152,46608,192.168.1.190,53,udp,dns,0.000549,0,298,...,0,0,-,-,-,bad_UDP_checksum,-,F,0,normal

In [21]:
df.shape[0]

1000000

In [13]:
normals = df.loc[df['type']=='normal']

In [43]:
import os
from turtle import mode

def combine_or_extract_normal_csv(csv_folder,  mode="normal"):
    """
    Extracts rows with "type" == "normal" from all CSV files in the given folder
    or combines all CSV files without filtering, depending on the mode,
    and saves them to a single output CSV file.

    """
    final_data = []
    total_rows = 0
    all_normal_rows = 0
    output_file = normal_data_csv if mode == "normal" else all_network_data_csv
    print(f"Mode is set to '{mode}'. Output will be saved to {output_file}")
    if os.path.exists(output_file):
        print(f"Output file {output_file} already exists. Please remove it before running the script.")
        return
    
    # Iterate through all files in the folder
    for filename in os.listdir(csv_folder):
        file_path = os.path.join(csv_folder, filename)
        
        # Check if the file is a CSV
        if not filename.endswith('.csv'):
            continue
        try:
            df = pd.read_csv(file_path)
            rows = df.shape[0]
            total_rows += rows
            if mode =="normal":
                # Filter rows where "type" is "normal"
                normal_df = df[df['type'] == 'normal']
                normal_rows = normal_df.shape[0]
                all_normal_rows += normal_rows
                
                # Append to the list of normal data
                final_data.append(normal_df)
                print(f"Processed {filename} - {len(normal_df)} normal rows")
            else:
                # combine all data
                final_data.append(df)
                print(f"Processed {filename} - {len(df)} rows")
        except Exception as e:
            print(f"Error processing {filename}: {e}")

    print(f"\nTotal rows processed: {total_rows}")
    print(f"Total normal rows found: {all_normal_rows}")
    
    # Combine all normal data into one DataFrame
    if final_data:
        combined_df = pd.concat(final_data, ignore_index=True)
        print("trying to save final on ",output_file)
        combined_df.to_csv(output_file, index=False)
        print(f"\nSaved {len(combined_df)} normal rows to {output_file}")
    else:
        print("No CSV files found or no  rows to save.")

# Example usage:
# combine_or_extract_normal_csv(csv_folder)
combine_or_extract_normal_csv(csv_folder, mode="all")

Mode is set to 'all'. Output will be saved to ../data/all_network_data.csv

C:\Users\ACER\AppData\Local\Temp\ipykernel_13776\3818833849.py:28: DtypeWarning: Columns (0: src_bytes) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

Processed Network_dataset_1.csv - 1000000 rows
Processed Network_dataset_10.csv - 1000000 rows
Processed Network_dataset_11.csv - 1000000 rows
Processed Network_dataset_12.csv - 1000000 rows
Processed Network_dataset_13.csv - 1000000 rows
Processed Network_dataset_14.csv - 1000000 rows
Processed Network_dataset_15.csv - 1000000 rows
Processed Network_dataset_16.csv - 1000000 rows
Processed Network_dataset_17.csv - 1000000 rows
Processed Network_dataset_18.csv - 1000000 rows
Processed Network_dataset_19.csv - 1000000 rows
Processed Network_dataset_2.csv - 1000000 rows
Processed Network_dataset_20.csv - 1000000 rows
Processed Network_dataset_21.csv - 1000000 rows
Processed Network_dataset_22.csv - 1000000 rows
Processed Network_dataset_23.csv - 339021 rows
Processed Network_dataset_3.csv - 1000000 rows
Processed Network_dataset_4.csv - 1000000 rows
Processed Network_dataset_5.csv - 1000000 rows
Processed Network_dataset_6.csv - 1000000 rows
Processed Network_dataset_7.csv - 1000000 rows
Processed Network_dataset_8.csv - 1000000 rows
Processed Network_dataset_9.csv - 1000000 rows

Total rows processed: 22339021
Total normal rows found: 0
trying to save final on  ../data/all_network_data.csv

KeyboardInterrupt:

In [26]:

normal_file = os.path.join("../data/outputs/normal_data.csv")
print("file is ",normal_file)
df = pd.read_csv(normal_file)
df.head()

file is  ../data/outputs/normal_data.csv

C:\Users\ACER\AppData\Local\Temp\ipykernel_13776\195724845.py:3: DtypeWarning: Columns (0: src_bytes, 1: uid) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(normal_file)

,ts,src_ip,src_port,dst_ip,dst_port,proto,service,duration,src_bytes,dst_bytes,...,http_status_code,http_user_agent,http_orig_mime_types,http_resp_mime_types,weird_name,weird_addl,weird_notice,label,type,uid
0,1554198358,3.122.49.24,1883,192.168.1.152,52976,tcp,-,80549.530260,1762852,41933215,...,0,-,-,-,bad_TCP_checksum,-,F,0,normal,NaN
1,1554198358,192.168.1.79,47260,192.168.1.255,15600,udp,-,0.000000,0,0,...,0,-,-,-,-,-,-,0,normal,NaN
2,1554198359,192.168.1.152,1880,192.168.1.152,51782,tcp,-,0.000000,0,0,...,0,-,-,-,bad_TCP_checksum,-,F,0,normal,NaN
3,1554198359,192.168.1.152,34296,192.168.1.152,10502,tcp,-,0.000000,0,0,...,0,-,-,-,-,-,-,0,normal,NaN
4,1554198362,192.168.1.152,46608,192.168.1.190,53,udp,dns,0.000549,0,298,...,0,-,-,-,bad_UDP_checksum,-,F,0,normal,NaN

In [4]:
def combine_or_extract_normal_csv2(csv_folder, mode="normal", max_rows=1_000_000):
    final_data = []
    total_rows = 0
    output_file = normal_data_csv if mode == "normal" else all_network_data_csv

    print(f"Mode: '{mode}' | Output: {output_file}")

    # for filename in os.listdir(csv_folder):
    #     if not filename.endswith('.csv'):
    #         continue
    #     df = pd.read_csv(csv_folder + '/' + filename, nrows=2)
    #     print(f"{filename}: {sorted(df.columns.tolist())}")

    # return

    if os.path.exists(output_file):
        print(f"Output file already exists. Remove it before running.")
        return

    csv_files = [f for f in os.listdir(csv_folder) if f.endswith('.csv')]
    rows_per_file = max_rows // len(csv_files)
    print(f"Found {len(csv_files)} CSV files | "
          f"Budget per file: {rows_per_file:,}")

    for filename in csv_files:
        file_path = os.path.join(csv_folder, filename)
        try:
            df = pd.read_csv(file_path)
            if 'uid' in df.columns:
                df = df.drop(columns=['uid'])
            total_rows += len(df)

            if mode == "normal":
                filtered = df[df['type'] == 'normal']
                final_data.append(filtered)
                print(f"  {filename}: {len(filtered):,} normal rows")

            else:
                # Sample per file before appending — never load 22M into memory
                if len(df) > rows_per_file:
                    n_types   = df['type'].nunique()
                    per_type  = rows_per_file // n_types
                    sampled = []
                    for t, group in df.groupby('type'):
                        sampled.append(group.sample(n=min(len(group), per_type), random_state=42))
                    filtered = pd.concat(sampled, ignore_index=True)
                else:
                    filtered = df

                final_data.append(filtered)
                print(f"  {filename}: {len(filtered):,} / {len(df):,} rows sampled")

        except Exception as e:
            print(f"  ERROR {filename}: {e}")

    print(f"\nTotal raw rows processed: {total_rows:,}")

    if final_data:
        combined_df = pd.concat(final_data, ignore_index=True)

        if 'ts' in combined_df.columns:
            combined_df = combined_df.sort_values('ts').reset_index(drop=True)
            print("Sorted by timestamp")

        # print(f"\nFinal distribution:")
        # print("-----------------",combined_df.head())
        # print(combined_df['type'].value_counts())
        # print(f"Total rows: {len(combined_df):,}")
        combined_df.to_csv(output_file, index=False)

        print(f"Saved to {output_file}")
    else:
        print("No data found.")

combine_or_extract_normal_csv2(csv_folder, mode="all", max_rows=1_000_000)

Mode: 'all' | Output: ../data/all_network_data.csv
Found 23 CSV files | Budget per file: 43,478

C:\Users\ACER\AppData\Local\Temp\ipykernel_18952\517906737.py:28: DtypeWarning: Columns (0: src_bytes) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

  Network_dataset_1.csv: 43,478 / 1,000,000 rows sampled
  Network_dataset_10.csv: 43,478 / 1,000,000 rows sampled
  Network_dataset_11.csv: 43,476 / 1,000,000 rows sampled
  Network_dataset_12.csv: 43,476 / 1,000,000 rows sampled
  Network_dataset_13.csv: 22,656 / 1,000,000 rows sampled
  Network_dataset_14.csv: 22,322 / 1,000,000 rows sampled
  Network_dataset_15.csv: 22,799 / 1,000,000 rows sampled
  Network_dataset_16.csv: 23,630 / 1,000,000 rows sampled
  Network_dataset_17.csv: 43,478 / 1,000,000 rows sampled
  Network_dataset_18.csv: 43,476 / 1,000,000 rows sampled
  Network_dataset_19.csv: 34,447 / 1,000,000 rows sampled
  Network_dataset_2.csv: 27,456 / 1,000,000 rows sampled
  Network_dataset_20.csv: 43,476 / 1,000,000 rows sampled
  Network_dataset_21.csv: 36,146 / 1,000,000 rows sampled
  Network_dataset_22.csv: 43,476 / 1,000,000 rows sampled
  Network_dataset_23.csv: 30,036 / 339,021 rows sampled
  Network_dataset_3.csv: 24,559 / 1,000,000 rows sampled
  Network_dataset_4.csv: 27,995 / 1,000,000 rows sampled
  Network_dataset_5.csv: 25,396 / 1,000,000 rows sampled
  Network_dataset_6.csv: 35,212 / 1,000,000 rows sampled
  Network_dataset_7.csv: 29,238 / 1,000,000 rows sampled
  Network_dataset_8.csv: 43,476 / 1,000,000 rows sampled
  Network_dataset_9.csv: 43,478 / 1,000,000 rows sampled

Total raw rows processed: 22,339,021
Sorted by timestamp
Saved to ../data/all_network_data.csv